name: Hello world workflow

on: 
  push:
    branches:
      - main
      - master
      - feature1
  pull_request:
    branches:
      - main
      - master
  # workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: helloworld
        run: echo "Hello world..."
        shell: bash
  
  bye:
    runs-on: ubuntu-latest
    steps:
      - name: bye git
        run: echo "byeee....."
        shell: bash
